/*
 * Builds the npm package into dist/.
 *
 * This is the second way the library ships. `pnpm registry:build` produces the
 * shadcn registry, where a component is copied into the consumer's own tree and
 * becomes theirs; this produces a normal versioned dependency for people who
 * would rather install than own. Both are generated from the same source, so
 * neither can drift from the other.
 *
 * There is no bundler here on purpose. Three reasons:
 *
 *  - `"use client"` has to survive per file. A bundler that merges modules has
 *    to be talked into preserving directives, and gets it wrong at exactly the
 *    boundary that matters. tsc emits one file per source file and keeps each
 *    file's directive prologue where it was.
 *  - tree-shaking is better when the files stay separate and every subpath is
 *    its own entry, so importing the button cannot drag in the calendar.
 *  - it adds no dependency to a repo that so far has needed none for this.
 *
 * What tsc will NOT do is rewrite the `@/...` aliases in the code it emits, so
 * that happens below. Run `pnpm package:build`.
 */

import { execFileSync } from "node:child_process";
import {
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";

const DIST = "dist";
const UI_SRC = "registry/minflow/ui";
const GLOBALS = "app/globals.css";

/* ------------------------------------------------------------- compile */

rmSync(DIST, { recursive: true, force: true });

console.log("- Compiling registry to dist...");
execFileSync("npx", ["tsc", "-p", "tsconfig.package.json"], { stdio: "inherit" });

/* ------------------------------------------------- rewrite the aliases */

/*
 * Every alias points into the registry, and the registry is what became dist,
 * so each one maps to a path relative to the emitted file. Order matters for
 * the same reason it does in tsconfig: `@/lib/` has to be tried before a bare
 * `@/` would swallow it.
 */
const ALIASES = [
  [/^@\/lib\//, "lib/"],
  [/^@\/components\/ui\//, "ui/"],
  [/^@\/registry\/minflow\//, ""],
];

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) out.push(...walk(path));
    else out.push(path);
  }
  return out;
}

const emitted = walk(DIST);
let rewritten = 0;

for (const file of emitted) {
  if (!/\.(js|d\.ts|js\.map|d\.ts\.map)$/.test(file)) continue;
  const isMap = file.endsWith(".map");
  let source = readFileSync(file, "utf8");
  const before = source;

  /*
   * Matches the specifier in `from "..."`, `import "..."` and the dynamic and
   * declaration forms, which is every place tsc can put one.
   */
  source = source.replace(/(["'])(@\/[^"']+)\1/g, (whole, quote, spec) => {
    const alias = ALIASES.find(([pattern]) => pattern.test(spec));
    if (!alias) return whole;

    const target = spec.replace(alias[0], alias[1]);
    let rel = relative(dirname(file), join(DIST, target)).replace(/\\/g, "/");
    if (!rel.startsWith(".")) rel = `./${rel}`;
    /*
     * An extension is not needed by bundlers and IS needed by Node's own ESM
     * resolver. Adding it costs nothing and makes the package work in both.
     * Type declarations keep the extensionless form, because a `.js` suffix in
     * a `.d.ts` import resolves to the sibling `.d.ts` anyway and the bare form
     * is what older TypeScript resolvers expect.
     */
    return `${quote}${file.endsWith(".d.ts") || isMap ? rel : `${rel}.js`}${quote}`;
  });

  if (source !== before) {
    writeFileSync(file, source);
    rewritten++;
  }
}
console.log(`- Rewrote aliases in ${rewritten} files.`);

/* --------------------------------------------------------- the barrel */

/*
 * A root entry that re-exports everything, for people who would rather write
 * one import line. It carries "use client" because almost everything it points
 * at is a client component, and a server file re-exporting them would make the
 * boundary depend on which component you happened to pull.
 *
 * Prefer the subpath (`@shekharp77/minflow/button`) in real apps: it is the
 * form that cannot pull in anything you did not ask for.
 */
const components = readdirSync(UI_SRC)
  .filter((f) => f.endsWith(".tsx"))
  .map((f) => f.replace(/\.tsx$/, ""))
  .sort();

const barrel = [
  '"use client";',
  "",
  "/* Generated by scripts/build-package.mjs. Do not edit. */",
  "",
  ...components.map((name) => `export * from "./ui/${name}.js";`),
  'export * from "./lib/motion.js";',
  'export * from "./lib/utils.js";',
  "",
].join("\n");

const barrelTypes = [
  "/* Generated by scripts/build-package.mjs. Do not edit. */",
  "",
  ...components.map((name) => `export * from "./ui/${name}";`),
  'export * from "./lib/motion";',
  'export * from "./lib/utils";',
  "",
].join("\n");

writeFileSync(join(DIST, "index.js"), barrel);
writeFileSync(join(DIST, "index.d.ts"), barrelTypes);

/* ---------------------------------------------------------- the styles */

/*
 * The token layer, taken from the stylesheet this site actually renders with,
 * so a consumer's colours are the ones in the screenshots rather than a copy
 * that drifted. The only thing removed is Tailwind's own import: the consumer
 * already pulls Tailwind in, and importing it twice duplicates preflight.
 */
const css = readFileSync(GLOBALS, "utf8")
  .replace(/^@import\s+["']tailwindcss["'];\s*$/m, "")
  .trimStart();

writeFileSync(
  join(DIST, "styles.css"),
  `/* minflow token layer. Generated from app/globals.css - do not edit. */\n\n${css}`
);

/* ------------------------------------------------------------- report */

/* README and LICENSE are not copied here: npm puts the ones at the repo root
   into every tarball on its own, and a second copy inside dist/ is just weight
   the consumer downloads twice. */

console.log(
  `✔ Built dist: ${components.length} components, ${emitted.length} emitted files, styles.css from ${GLOBALS}.`
);
